# Generated by Django 4.1.7 on 2023-09-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='income',
            field=models.IntegerField(default=0),
        ),
    ]
