# Generated by Django 4.1.7 on 2023-09-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetApp', '0002_budget_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcategory',
            name='category_budget',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='newcategory',
            name='name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='newlineitem',
            name='category',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newlineitem',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newlineitem',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
